### ISSUE TITLE
Dark mode for the website

### ISSUE THREAD

**Issue by Akshatchaube01** [amanjaiman1/Product_3D#1]
I would like to work on this issue , I would create a button on the top right corner to toggle between dark theme and light theme as the user wishes.

**Comment by rahultomarr** [comment]
I'm here to contribute to the GSSOC'23.
Please assign me to do that.

**Comment by amanjaiman1** [comment]
Let's connect first on LinkedIn and also WhatsApp (6378722785).

**Comment by amanjaiman1** [comment]
I assigned you guys, keep up the route , and please inform me whenever you made a change 😉

**Comment by neeraj542** [comment]
I want to work on this issue, please assign me so that I can show my work to you.
