### ISSUE TITLE
Complete The guide us page

### ISSUE THREAD

**Issue by kharshita590** [amanjaiman1/Product_3D#107]

**Comment by kharshita590** [comment]
hey thanks for assigning! I just want to know one thing can you please explain how your guide book page shiuld look like, so i will work according to it

**Comment by amanjaiman1** [comment]
Can you please contact me on Discord?

**Comment by kharshita590** [comment]
yeah

**Comment by amanjaiman1** [comment]
AMANJAIMAN#3931

**Comment by amanjaiman1** [comment]
I think you cant complete it
