### ISSUE TITLE
add contributors graph 

### ISSUE THREAD

**Issue by S-ishita** [amanjaiman1/Product_3D#11]
I want to add contributors graph in readme.Please assign this issue to me under GSSOC

**Comment by amanjaiman1** [comment]
Keep up your smart work, ishita!

**Comment by amanjaiman1** [comment]
Thats looking so good , it will look better if the comment option will be in right bottom side because in the center its tends to overlap some other things

**Comment by S-ishita** [comment]
which comment option are you talking about?

**Comment by amanjaiman1** [comment]
Sorry for the previous message

**Comment by S-ishita** [comment]
hey @amanjaiman1  can i close this issue now..as it is completed now?
