### ISSUE TITLE
Sign In button is not working

### ISSUE THREAD

**Issue by akshaysoni10** [amanjaiman1/Product_3D#111]
When I click on signIn button it's not working. I would like to add attractive sign in page with better UI and also wants to make signIn button attractive.
Please assign me under GSSOC' 23.

**Comment by amanjaiman1** [comment]
I think someone is already doing that work , please check the recents issue and then inform me in which issue and who is working
Then i assign you perfectly

**Comment by akshaysoni10** [comment]
Ok

**Comment by amanjaiman1** [comment]
@akshaysoni10  can you do other implementation on website or i just close the issue?

**Comment by akshaysoni10** [comment]
Which type of implementation you want?

**Comment by amanjaiman1** [comment]
We need react or three.js developers to develop more pages on the website, if you are in then DM me on Discord or i will close this issue.

Discord - AMANJAIMAN#3931
