### ISSUE TITLE
Create a contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [amanjaiman1/Product_3D#117]
create the avatar of the contributor like we have on github at the end of each repo, a card would make it look more attarctive.
we could implement the github api to fetch the contributors data dynamically, we could make it into a card with the view profile button that would redirect you to their github profile

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by karthiknadar1204** [comment]
Will get working asap

**Comment by amanjaiman1** [comment]
@karthiknadar1204  1week more?

**Comment by karthiknadar1204** [comment]
Yes, started work yesterday only after exams.have design layout in my mind,implementing it

**Comment by amanjaiman1** [comment]
Ohk then

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.
