### ISSUE TITLE
Add a 3d Model of T shirt with Textures , Shadow and Orbit Controls 

### ISSUE THREAD

**Issue by Him7n** [amanjaiman1/Product_3D#12]

**Comment by amanjaiman1** [comment]
Can you please elaborate this..

**Comment by PatilHarshh** [comment]
intrested @amanjaiman1 please assign it to me

**Comment by abhinow01** [comment]
hey @amanjaiman1 , can you assign this issue to me ?

**Comment by amanjaiman1** [comment]
Guys guys please elaborate the work first like what will you change, etc

**Comment by Sitzz23** [comment]
I'm interested, @amanjaiman1 can you assign it to me
I'll render the t-shirt model, and add hover controls

**Comment by amanjaiman1** [comment]
ohk then i am assigning only @Sitzz23

**Comment by PatilHarshh** [comment]
@amanjaiman1 i do not have prior knowledge of the three js ,but i will try if assigned in Collaboration

**Comment by abhinow01** [comment]
Hey aman ,
I am not well equipped with the knowledge of three js , I am a beginner,
but I am eager  learn on the way and contribute to this project , please
let me know how can I help and how should I proceed .

**Comment by amanjaiman1** [comment]
@PatilHarshh DM me on Discord

**Comment by balaji-sivasakthi** [comment]
@Him7n  Since there hasn't been any activity or description provided, we will proceed to close it for now.
