### ISSUE TITLE
Login and sign up page with beautiful design 

### ISSUE THREAD

**Issue by kunalkashyap-1** [amanjaiman1/Product_3D#124]
![image](https://github.com/amanjaiman1/Product_3D/assets/91254500/4d40834c-e2b7-417c-8631-81a4765ca736)

this is a template which the login and sign up page would be based on the right hand side blue circle would be replaced by a 3d design.

I'm in GSSoC'23.
Do assign me this issue.

**Comment by amanjaiman1** [comment]
Ohk that's looking great

**Comment by amanjaiman1** [comment]
And also have to add some framer Motion animation in 3D images ok

**Comment by kunalkashyap-1** [comment]
sure i'll try my best, btw what would be the deadline for this as i have some college work to take care of

**Comment by amanjaiman1** [comment]
This is in critical label but I can give you last 2-3 days

**Comment by kunalkashyap-1** [comment]
sure that's fine

**Comment by kunalkashyap-1** [comment]
Do provide appropriate labels to this issue
