### ISSUE TITLE
Styling Navbar responsive and adding bars when in mobile size

### ISSUE THREAD

**Issue by Akanksha-202** [amanjaiman1/Product_3D#126]
I wanted to add bars when the screen is minimized and toggle the bars (hamburger) to view the navbar options.
![image](https://github.com/amanjaiman1/Product_3D/assets/100708686/d1b3f2d9-463c-4f41-a7ab-c8c88b06fa2d)
The navbar options are not in sync as of now.

Would really like to work on this issue.
Kindly assign the issue under the GSSoC'23 label:)

**Comment by amanjaiman1** [comment]
Wait @Akanksha-202 , we are updating the new UI after that you can contribute

**Comment by amanjaiman1** [comment]
Hey !
Now you can checkout our Website and Design.md file also then you can choose what you want to do
