### ISSUE TITLE
{GSSOC'23}Add a footer  

### ISSUE THREAD

**Issue by thekirti02** [amanjaiman1/Product_3D#128]
I would like to add a perfect footer for this website. 
Please assign this issue to me.

**Comment by gaurimadan** [comment]
hello
As I saw your website, there is a scope of improvement in designing. Give me the chance to apply my skills and add an attractive and informative footer. Kindly assign this to me under Gssoc'23.

**Comment by SurajPratap10** [comment]
Assigned @thekirti02

**Comment by thekirti02** [comment]
Thank you for assigning me.
