### ISSUE TITLE
{GSSOC'23}Improve the UI of home page 

### ISSUE THREAD

**Issue by thekirti02** [amanjaiman1/Product_3D#130]
I want to improve the UI of the Home page so that it will look beautiful, and I will add some features like social media section over there.

<img width="946" alt="issue8 3d designer tshirt " src="https://github.com/amanjaiman1/Product_3D/assets/105008820/8fa0da49-ee59-47fa-ad29-a1e0d025349a">

**Comment by amanjaiman1** [comment]
emm wait for tommorow @thekirti02 , after the design.md updation , we will notify for your work distribution

**Comment by thekirti02** [comment]
okay Thank you, I am waiting...

**Comment by amanjaiman1** [comment]
Please join our Project Discord Team Server @thekirti02

**Comment by amanjaiman1** [comment]
> Please join our Project Discord Team Server @thekirti02

https://discord.gg/aSPQFFnY

**Comment by thekirti02** [comment]
joined the Server
