### ISSUE TITLE
Adding section of material 

### ISSUE THREAD

**Issue by Anishkagupta04** [amanjaiman1/Product_3D#132]
You can add a section related to which material is of tshirt like cotton,polyester,nylon,etc

**Comment by gaurimadan** [comment]
I am a UX/UI designer. I would like to work towards adding this particular section. Kindly assign me under Gsscoc'23.

**Comment by Anishkagupta04** [comment]
Require permission of the owner !!

**Comment by amanjaiman1** [comment]
@Anishkagupta04 you are in our discord team server? 
If not kindly join us https://discord.gg/aSPQFFnY

**Comment by Anishkagupta04** [comment]
Okay I did

**Comment by Akanksha038** [comment]
Hello @amanjaiman1 Sir,
I am a Frontend Developer. I want to add section of material. Can you please assign this issue to me? I would like to work on this issue under GSSOC'23.
