### ISSUE TITLE
Front interface should be attractive 

### ISSUE THREAD

**Issue by Anishkagupta04** [amanjaiman1/Product_3D#133]
Add some attractive colour to your front face

**Comment by amanjaiman1** [comment]
Wait for the final design , we would provide your work information

**Comment by Akanksha038** [comment]
Hello @amanjaiman1 Sir,
I am a Frontend Developer. I want to make Front interface much more attractive. Can you please assign this issue to me? I would like to work on this issue under GSSOC'23.

**Comment by amanjaiman1** [comment]
@Akanksha038 We have a team , they are contributing on specific works.
If you want to join the team and wanna contribute on other works then inform me
