### ISSUE TITLE
3d rotation of tshirt 

### ISSUE THREAD

**Issue by Anishkagupta04** [amanjaiman1/Product_3D#134]
Stickers And 3d rotation of tshirt should be there

**Comment by amanjaiman1** [comment]
here three.js developer needed so I can personally help in this .

**Comment by Akanksha038** [comment]
Hello @amanjaiman1 Sir,
I worked on Blender and Unity. Can you please assign this issue to me. I would like to work on this issue under GSSOC'23.

**Comment by amanjaiman1** [comment]
You can join our team and start working on the project - https://discord.gg/qbBP6zHx
