### ISSUE TITLE
addition of a carousel

### ISSUE THREAD

**Issue by gaurimadan** [amanjaiman1/Product_3D#135]
I want to add a carousel of three to four images of how tshirts might look, materials available and try now slide.It would make the website more eye catchy and fascinating.

**Comment by gaurimadan** [comment]
Kindly assign me the issue under Gssoc'23.

**Comment by SurajPratap10** [comment]
Assigend @gaurimadan

**Comment by bhoomikhurana** [comment]
Has this work been done?I'd like to take this issue

**Comment by gaurimadan** [comment]
I am on it

**Comment by amanjaiman1** [comment]
@gaurimadan  please give a update otherwise i have to close this
