### ISSUE TITLE
[FEATURE] Scroll to top feature .

### ISSUE THREAD

**Issue by ManishaSwain8** [amanjaiman1/Product_3D#138]
As I can see the website is under construction ,  as much as the components will increase scrolling will be required. It will be fair to add a scroll to top button , so that where ever the person is at , can directly scroll to top which will make it user friendly.
If this new feature is required do assign it to me under GSSOC 2023.
Changes will be done in no time. ! : |)

**Comment by amanjaiman1** [comment]
Hey @ManishaSwain8 , first we are implementing our design i.e. blueprint of website and secondly you can create the "scroll to top button" Component in the component folder and then we will import in App.jsx file

SO you can go ahead

**Comment by ManishaSwain8** [comment]
Oh okay ..on it !

**Comment by amanjaiman1** [comment]
Hey @ManishaSwain8 , now you can start the work 
make a beautiful scroll to top button only for home page

**Comment by ManishaSwain8** [comment]
Sure !

**Comment by amanjaiman1** [comment]
Which library ?
