### ISSUE TITLE
change favicon

### ISSUE THREAD

**Issue by S-ishita** [amanjaiman1/Product_3D#14]
I want to change the favicon .Please assign this issue to me under GSSOC

**Comment by creator79** [comment]
Hello! I would like to contribute to this project and improve the] icons section. Is this issue still open or has it been assigned? GSSOC23I believe I can make valuable contributions in enhancing the design and functionality of the icons. Thank you!

**Comment by amanjaiman1** [comment]
Not assigned yet , lemme assign to you and make the valuable.

**Comment by creator79** [comment]
@amanjaiman1  thanks for assingned me i have start working on this ASAP

**Comment by S-ishita** [comment]
Hey @amanjaiman1 ideally this should be assigned to me ..i opened this issue
Kindly unassign the other person

**Comment by amanjaiman1** [comment]
@S-ishita sorry for that , now i also assigned you, ok!
