### ISSUE TITLE
Adding hover effect on nav elements

### ISSUE THREAD

**Issue by Anshkaran7** [amanjaiman1/Product_3D#146]
I have a suggestion to improve the user interface (UI) by incorporating hover effects  for navbar elements [Home, Guide Books ,Customize etc]. Currently, the navbar elements lack a smooth hover transition and a specified hover color, which affects the overall user experience and visual consistency.

I would be thrilled to contribute to this and kindly request to be assigned this task under GSSOC'23

![Screenshot 2023-05-27 202950](https://github.com/amanjaiman1/Product_3D/assets/106963118/6c572316-be93-493e-a494-3fbbbe832b37)

**Comment by amanjaiman1** [comment]
Go Ahead !

**Comment by Anshkaran7** [comment]
how i get the label of gssoc??
