### ISSUE TITLE
The home page of the website has a "header" text at the top. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [amanjaiman1/Product_3D#159]
**Describe the bug**
The home page of the website has a "header" text at the top. It looks very unprofessional.

**Expected behavior**
There must not be any such text

**Screenshots**
![isuue_header](https://github.com/amanjaiman1/Product_3D/assets/116020663/2c3ae4ea-9299-46fc-a8b5-62fe3c48e4a8)

**Additional context**
Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23.

**Comment by amanjaiman1** [comment]
We already updating the Navbar @1Shubham7 , if you want to contribute other works then inform me

**Comment by 1Shubham7** [comment]
Ok @amanjaiman1
