### ISSUE TITLE
Dark Mode is not working 

### ISSUE THREAD

**Issue by Subby575** [amanjaiman1/Product_3D#160]
**Describe the bug**
Dark mode is not working, the background color is not changing.

**Expected behavior**
The background should change from white/light mode to black/dark blue in color when the dark mode toggle button is clicked.

**Screenshots**
![gssoc](https://github.com/amanjaiman1/Product_3D/assets/114326247/dc2911bb-f3f7-4881-84ac-51274b33d442)
dark mode  

![gssoc1](https://github.com/amanjaiman1/Product_3D/assets/114326247/4d80a9a0-7023-49ae-818c-429a8197a0e9)
light mode

I want to work on this issue. Please assign me this issue.

**Comment by amanjaiman1** [comment]
Actually we removed the dark mode on home page because of theme settlement but if you want to contribute other works then inform me
