### ISSUE TITLE
[DOCS] Add Contributors Graph

### ISSUE THREAD

**Issue by Shiva-Sai-ssb** [amanjaiman1/Product_3D#165]
* I would like to incorporate a contributor graph in the README.md file as a means of acknowledging and appreciating the work of contributors. I kindly request to be assigned this particular issue.
* Here is an example of the work I aspire to undertake within this project.

![Screenshot (80)](https://github.com/amanjaiman1/Product_3D/assets/112751524/70f1d1a9-08c8-49c1-9864-9515289ab71b)

**Comment by amanjaiman1** [comment]
Go ahead

**Comment by Shiva-Sai-ssb** [comment]
Hello @amanjaiman1, I was wondering if there are any concerns or issues with my pull request as it hasn't been merged yet.
