### ISSUE TITLE
Erroneous FAQ Page

### ISSUE THREAD

**Issue by soumizde** [amanjaiman1/Product_3D#176]
### Describe the bug

If you type /faq after the website link, you will land on an error page. Whereas if you click on faq - it works. It shouldn't be that way cause there is some ambiguity. 

### Expected behaviour

The error page shouldn't appear when /faq is typed

### Screenshots

![Screenshot (14)](https://github.com/amanjaiman1/Product_3D/assets/104732379/55d27290-be3e-45e7-a476-3804bf1946ee)
![Screenshot (15)](https://github.com/amanjaiman1/Product_3D/assets/104732379/d8ab9444-c06d-4332-8a4e-e43fada00426)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Thanks , you found that one probem , go ahead

**Comment by soumizde** [comment]
Okay never mind I got it
