### ISSUE TITLE
Add Slider to the reviews section

### ISSUE THREAD

**Issue by 007aneesh** [amanjaiman1/Product_3D#179]
### Is your feature request related to a problem? Please describe.

The review section is static and I want to make it like a slider So please assign it to me under GSSoC'23 label.

![image](https://github.com/amanjaiman1/Product_3D/assets/90706436/1e279335-4fac-4da8-a3bb-818f016bac2d)

### Describe the solution you'd like

So I want to add the reviews in the form of slider, reviews will auto slide that make the website looks cool

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Good , Go ahead then !

**Comment by 007aneesh** [comment]
Thanks please also add the required labels on this issue and I want to ask that for the contribution to be counted do I need to have the label on the issue or both issue and PR? @amanjaiman1

**Comment by amanjaiman1** [comment]
focus on your work , i will do these things dont worry

**Comment by 007aneesh** [comment]
Ok working on it!

**Comment by 007aneesh** [comment]
Add gssoc + level label to this issue @amanjaiman1

**Comment by amanjaiman1** [comment]
Done bhai , but now please complete in the objects layout as we discussed earlier

**Comment by 007aneesh** [comment]
Will create a pr by midnight! 👍
