### ISSUE TITLE
BUG: TESTIMONIALS SECTION ARE NOT RESPONSIVE

### ISSUE THREAD

**Issue by 0xabdulkhalid** [amanjaiman1/Product_3D#180]
### Describe the bug

- This bug is about the irresponsive behaviour of testimonals section for mobile view
- The Testimonial component itself being cut-off during the mobile view
- Every site want to responsive regardless of device, whether it can be a Tablet, laptop etc

### Expected behaviour

The testimonial section need to responsive on mobile view

### Screenshots

![Screenshot_2023-05-30-18-22-29_1366x768](https://github.com/amanjaiman1/Product_3D/assets/92252895/ce6ed5f2-cc28-41f5-9c70-76169fddbc6f)
![Screenshot_2023-05-30-18-26-34_1366x768](https://github.com/amanjaiman1/Product_3D/assets/92252895/85d3c734-6ce6-46cd-a2ff-1c9d43859811)

### Additional context

- I'm `gssoc23`  contributor, please consider me to solve this issue by assigning me to this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Go Ahead and complete it ASAP!

**Comment by 0xabdulkhalid** [comment]
Hello @amanjaiman1, I'm not willing to work on this issue. (I have no time due to exams)

Sorry for the inconvenience, I'm closing this issue!
