### ISSUE TITLE
Show Contributers Detail on Contributers page

### ISSUE THREAD

**Issue by shuklabhisekh** [amanjaiman1/Product_3D#181]
### Is your feature request related to a problem? Please describe.

On clicking on contributors in Navbar it takes us to page where it shows 404 not found
![image](https://github.com/amanjaiman1/Product_3D/assets/95949460/a197a34f-d21b-465e-8f62-273fc8d561e1)
a 

### Describe the solution you'd like

Instead of showing 404 not found create a contributed page that showing all the contributor's details which are showing on Homepageshowsshows

### Additional context

I want to work on this issue under GSSOC'23. please assign this to me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
See i have aleady a team member for this work but i want you to do this with best UI work , understood?

**Comment by amanjaiman1** [comment]
and tell me how would long it will take?

**Comment by amanjaiman1** [comment]
Should i Close this one?

**Comment by amanjaiman1** [comment]
Okay , complete it ASAP ! with best UI

**Comment by shuklabhisekh** [comment]
Hey @amanjaiman1, I've created a PR for this issue. Please review it.

**Comment by amanjaiman1** [comment]
Imp. - Do Star the repo .
