### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by parasss19** [amanjaiman1/Product_3D#183]
## Current
Navbar is not fixed so every time I have to scroll to come back to top and it consume users lots of time

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Good Points , go ahead !

**Comment by parasss19** [comment]
> but wait , i m merging a PR after this you can start the work , by cloning new file

Please assign me this issue after mergin PR

**Comment by amanjaiman1** [comment]
Now you can start your work , once you done inform me on Discord before creating the PR

**Comment by parasss19** [comment]
> Now you can start your work , once you done inform me on Discord before creating the PR

After completing my work can i inform you here only as my discord is having some trouble since few days

**Comment by amanjaiman1** [comment]
Ohk no worries

**Comment by parasss19** [comment]
## Hi @amanjaiman1 I am not able to install server dependencies
<img width="960" alt="2023-05-30 (2)" src="https://github.com/amanjaiman1/Product_3D/assets/101205226/ccbd45fd-6941-453e-9cd9-ba9efa876df9">

**Comment by parasss19** [comment]
Hi @amanjaiman1 I have one problem 
Any changes that I have made in code doesn't reflect in the website . But when I made changes on console it reflect in the webstie

**Comment by amanjaiman1** [comment]
Please clone again the repo
