### ISSUE TITLE
Scrollbar Enhancement

### ISSUE THREAD

**Issue by soumizde** [amanjaiman1/Product_3D#188]
### Is your feature request related to a problem? Please describe.

I want to create a customized nav bar for the new revamped website. It is currently a bland and default gray scrollbar

### Describe the solution you'd like

I want to create a scrollbar with a colour and a feel similar to that of the theme of thw website

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Go Ahead

**Comment by amanjaiman1** [comment]
Keep it blue , because out site theme gonna blue and white
