### ISSUE TITLE
API issue and Landing page  on mobile and PC both can be better 

### ISSUE THREAD

**Issue by Shubham185y** [amanjaiman1/Product_3D#19]
Please assign this to me so that i can start working on this
![image](https://github.com/amanjaiman1/Product_3D/assets/100077254/25eb234f-4725-4c63-b89a-1a1c5f353e6c)

**Comment by amanjaiman1** [comment]
Actually the server folder have a build error , i've been trying for a long time but it failed on render.
If you can do it , will be great

**Comment by Shubham185y** [comment]
![image](https://github.com/amanjaiman1/Product_3D/assets/100077254/a5d6aaff-50e1-41a5-a26b-4f4f0bf14652)
![image](https://github.com/amanjaiman1/Product_3D/assets/100077254/9d46266a-a97f-4b38-aa13-57d925860ad0)
Please help me in resolving this issue

**Comment by Shubham185y** [comment]
the server started but what about this 
![image](https://github.com/amanjaiman1/Product_3D/assets/100077254/b2340fb6-6fb7-448e-876d-f606f7d979e0)
please help me in this as well

**Comment by amanjaiman1** [comment]
bro you can again download the new zip file , may be old have some issue

**Comment by amanjaiman1** [comment]
Oh , actually you can remove the canvas importing, which creating the issue
