### ISSUE TITLE
adding curser pointer in the footer links

### ISSUE THREAD

**Issue by Iamdivyak** [amanjaiman1/Product_3D#192]
### Is your feature request related to a problem? Please describe.

when someone hovers over the footer links. its curser does not change into pointer. so it becomes quite confusing to the user whether is this clickable or not.

<img width="943" alt="image" src="https://github.com/amanjaiman1/Product_3D/assets/102896170/d4728e14-4965-4b62-a380-1caece2dd9df">

### Describe the solution you'd like

it would be helpful to users to change the curser into pointer by hover over the likes.

I would like to work on this issue.
kindly assign it to me under GSSOC'23 contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by balaji-sivasakthi** [comment]
We appreciate your feedback regarding the issue with the footer links. We have addressed the problem, and the cursor now changes to a pointer on hover. Thank you for bringing this to our attention, and we value your contribution to improving our user experience. If you have any more suggestions or encounter any other issues, please don't hesitate to reach out.
