### ISSUE TITLE
Hero Section Text Effect

### ISSUE THREAD

**Issue by parasss19** [amanjaiman1/Product_3D#195]
### The landing page of your website is looking simple and less attreactive

<img width="960" alt="2023-05-31 (3)" src="https://github.com/amanjaiman1/Product_3D/assets/101205226/18283e29-30e3-4404-b16f-58156e6f84d3">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Not Typewriter bro, any other effect please

**Comment by parasss19** [comment]
> Not Typewriter bro, any other effect please

Ok so tell me the effect you want?

**Comment by amanjaiman1** [comment]
like drop down or raising effect
or can you send me some examples of effects like any resources where i can see these all

**Comment by abhinav-m22** [comment]
Hey @amanjaiman1 
I can add the required animations. I have worked with similar effects before.
Please assign me the issue as it is inactive since 3 weeks
