### ISSUE TITLE
No option to move the added logo on the t-shirt and text styling missing.

### ISSUE THREAD

**Issue by AniketDutta007** [amanjaiman1/Product_3D#2]
I have observed the application lacks movement of logos on the t-shirt and I feel there should be an option to add text with customization on the t-shirt.

**Comment by AniketDutta007** [comment]
I would like to work on this issue for my GSSOC'2023.

**Comment by amanjaiman1** [comment]
Hey, i would like to make a separate branch for this feature but can you tell me how we can do it?

**Comment by AniketDutta007** [comment]
We will need to re-render the scene based on cursor movements to reposition the logo.

**Comment by amanjaiman1** [comment]
Do you want to work on this because it will implement with three.js so we need developers 
So are you in or out?

If in join the discord, i will send the  link
