### ISSUE TITLE
Add landing page for guide book 

### ISSUE THREAD

**Issue by Kalivarapubindusree** [amanjaiman1/Product_3D#203]
### Is your feature request related to a problem? Please describe.

Landing page for the guide book and contributors show error .

### Describe the solution you'd like

I want to add guide book landing page for the website.
 please assign me this task @amanjaiman1 

### Describe alternatives you've considered

I want to create good user experience for the landing page of guide book.

### Additional context

gssoc'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
We don't have enough context for this page yet @Kalivarapubindusree 
But we will implement that after our website is going to be completed.

**Comment by amanjaiman1** [comment]
Do you want to work on or should i close the issue?

**Comment by Kalivarapubindusree** [comment]
If you assign me then I will do the task sir @amanjaiman1 you didn't confirm my task assignment. If you confirm my task assignment then I start work on that page today itself

**Comment by amanjaiman1** [comment]
How much time you will take to complete this

**Comment by Kalivarapubindusree** [comment]
Probably two or three days @amanjaiman1

**Comment by amanjaiman1** [comment]
Ohk then Do it , for reference checkout the readme and use chatGPT  for generating texts
 

Note - Please do not mention DalleAI , we are updating the Readme for this 
Do instead, mention Unsplash Image generator ok

**Comment by amanjaiman1** [comment]
May you please contact me on Discord?

**Comment by amanjaiman1** [comment]
Do Star the repo before starting your work.

**Comment by Kalivarapubindusree** [comment]
Need some information what kind of webpage must be your guide book webpage and what are the requirements must be in that page like in the guide book contains guidelines for contributions or guidelines for how to use this website?

**Comment by amanjaiman1** [comment]
You already have discussed me on discord na

**Comment by amanjaiman1** [comment]
Working or not?

**Comment by amanjaiman1** [comment]
Ohk then i'm closing this issue
