### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by suryanshsoni120** [amanjaiman1/Product_3D#204]
### Is your feature request related to a problem? Please describe.

Implement a toggle mode feature through which user can view website in dark mode/light mode.

### Describe the solution you'd like

Add functionality on the navbar through which the user can change the mode of the website. I would like to contribute to this issue under GSSOC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Hey @suryanshsoni120 , have you started working on that or not ?

**Comment by amanjaiman1** [comment]
Do Star the repo before starting your work.

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by shimmer12** [comment]
kindly assign me this issue under gssoc label as it is not closed

**Comment by balaji-sivasakthi** [comment]
There is no dark theme UI design for now.
