### ISSUE TITLE
Blog Page UI Design

### ISSUE THREAD

**Issue by MohamedMafaz** [amanjaiman1/Product_3D#210]
### Is your feature request related to a problem? Please describe.

Blog Page attracts more customers. So, we need to do it

### Describe the solution you'd like

I made an attractive UI for it

### Describe alternatives you've considered

There is no alternative for it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MohamedMafaz** [comment]
Created a **Pull Request**

**Comment by amanjaiman1** [comment]
Most valuable contributor in UX
