### ISSUE TITLE
I would like to add sign in with google along with forget password functionality from backend

### ISSUE THREAD

**Issue by AKsHaT123456A** [amanjaiman1/Product_3D#213]
### Is your feature request related to a problem? Please describe.

Yes , as signing in with google is good for user experience and also having a forgot password facility too helps.

### Describe the solution you'd like

I would like to implement sign in with google through OAUTH and forget password through express.js.
Kindly assign me this under gssoc'23.

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
How much time you will take?
And also message me on Discord , we have a team, if you wanna join.

**Comment by AKsHaT123456A** [comment]
Will complete it before 4th of June. Yes , sure can you provide me your discord

**Comment by AKsHaT123456A** [comment]
As it takes time to set up and store information.

**Comment by amanjaiman1** [comment]
Discord - AMANJAIMAN#3931
Pages front end done , you have to just implement the backend

**Comment by AKsHaT123456A** [comment]
Okay..i will complete it within 2 days.

**Comment by AKsHaT123456A** [comment]
Hi @amanjaiman1 as the backend is shifted on firebase what should i do raise a new issue or work under this  issue?

**Comment by amanjaiman1** [comment]
You can work with the team bhai

**Comment by AKsHaT123456A** [comment]
Ok
