### ISSUE TITLE
The website does not have meta tags with descriptions.

### ISSUE THREAD

**Issue by M-A-N-I-K** [amanjaiman1/Product_3D#215]
### Describe the bug

-     Issue: The website does not have meta tags with descriptions.
-     Impact: This means that the website is not as visible in search results, and users are less likely to click on the website's links.
    

### Expected behaviour

- Resolution: The website should add meta tags with descriptions to all of its pages. This will help the website rank higher in search results and attract more visitors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by Visbhavesh** [comment]
Please assign me.

**Comment by amanjaiman1** [comment]
Where you gonna add these meta tags and you know SEO properly?

**Comment by M-A-N-I-K** [comment]
@amanjaiman1 It is added in index.html file and yup i know SEO to some extent that it will increase ranking of website

**Comment by amanjaiman1** [comment]
Good, go ahead

**Comment by amanjaiman1** [comment]
Do Star the repo before starting your work.
