### ISSUE TITLE
Design a more new 3D Model of T shirt with Textures and more features.

### ISSUE THREAD

**Issue by MohnishK7** [amanjaiman1/Product_3D#22]
Hii @amanjaiman1 assign me and make it under **Gssoc 23**
**3D Models and Animations:**
Utilize popular libraries like Three.js or Babylon.js to render 3D models and animations on the website.
Create visually appealing 3D scenes, incorporating lighting, textures, and realistic physics.
Implement smooth animations and transitions to enhance user engagement.
Develop a responsive website layout using React and CSS frameworks, ensuring optimal user experience across various devices and screen sizes.
Employ responsive design principles to adapt the **3D elements** and **UI components** to different screen resolutions.

**Comment by amanjaiman1** [comment]
I just want to know what changes you want to do in this project ?

**Comment by MohnishK7** [comment]
Improve the GUI and add more editing features to models **--->** like adding different designs in shirts

**Comment by amanjaiman1** [comment]
ohk great, lets go

**Comment by MohnishK7** [comment]
Thank you so much :)

**Comment by MohnishK7** [comment]
can you please add the GSSOC 23 label.
