### ISSUE TITLE
Adding error 404 page

### ISSUE THREAD

**Issue by VC6378** [amanjaiman1/Product_3D#23]
Heyy,
I would like to add an error 404 page for the website.
Thanks and regards,
Vibhuti Chandrakar

**Comment by amanjaiman1** [comment]
Go ahead !

**Comment by PatilHarshh** [comment]
@amanjaiman1  please assign it to me

**Comment by VC6378** [comment]
Heyy, @amanjaiman1, can you re-assign me again, I unassigned my self by mistake.

**Comment by PatilHarshh** [comment]
hello @amanjaiman1 i am facing some issue can we you provide your handle to chat?

**Comment by amanjaiman1** [comment]
My WhatsApp no - 6378722785
