### ISSUE TITLE
Newsletter Page Design

### ISSUE THREAD

**Issue by gaurimadan** [amanjaiman1/Product_3D#237]
### Is your feature request related to a problem? Please describe.

I know designing, I want to create a web design for your newsletter page. Kindly assign me this task under Gssoc.

### Describe the solution you'd like

I would design a web page for it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by balaji-sivasakthi** [comment]
@gaurimadan ?
