### ISSUE TITLE
Making Cards more Attractive

### ISSUE THREAD

**Issue by nitin-pandita** [amanjaiman1/Product_3D#238]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/amanjaiman1/Product_3D/assets/91310284/08977fd1-c4de-46f5-94d7-aa3a0f425329)

### Describe the solution you'd like

Adding more styling to the card section like adding some shadow at the back making it more pretty and also adding some hover effect to make it look good

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Ohk , go ahead !

**Comment by nitin-pandita** [comment]
> Ohk , go ahead !

Thanks @amanjaiman1

**Comment by nitin-pandita** [comment]
> Ohk , go ahead !

Please make it label under ggsoc

**Comment by amanjaiman1** [comment]
First complete it

**Comment by nitin-pandita** [comment]
> First complete it

Ok.

**Comment by Abhinavcode13** [comment]
@amanjaiman1 please assign this to me , its been 1 week still no response from other contributor

**Comment by balaji-sivasakthi** [comment]
@Abhinavcode13 create a new issue if you want to enhance the current card because I'm going to close this issue.
