### ISSUE TITLE
 Want to add Sign Up and Log In page.

### ISSUE THREAD

**Issue by Nikita110602** [amanjaiman1/Product_3D#239]
### Is your feature request related to a problem? Please describe.

We should add Sign Up and Log In Page in this project for better user interaction.

![Screenshot (60)](https://github.com/amanjaiman1/Product_3D/assets/111515819/075d1595-e199-4b7b-a282-cab4fed152f5)

### Describe the solution you'd like

I have a very good design of sign up and log in page in react.js.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nikita110602** [comment]
pls assign me this work. I want to contribute in your project.

**Comment by amanjaiman1** [comment]
Hey @Nikita110602 , login and signup page are already integrated.

**Comment by deepshikha2708** [comment]
@amanjaiman1 where can we can see those pages?
