### ISSUE TITLE
Want to add TRY FREE page.

### ISSUE THREAD

**Issue by Nikita110602** [amanjaiman1/Product_3D#240]
### Is your feature request related to a problem? Please describe.

I want to add a page in TRY FREE section .

### Describe the solution you'd like

In TRY FREE section the user can sign up and start the TRY FREE course.

### Describe alternatives you've considered

![Screenshot (60)](https://github.com/amanjaiman1/Product_3D/assets/111515819/a9328ea6-c500-4056-a0a7-adca79c1e8a3)

I want to add some information and data in TRY FREE section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nikita110602** [comment]
Pls assign me this work . I want to contribute in your work.

**Comment by balaji-sivasakthi** [comment]
@Nikita110602 Hi, could you explain it more?

**Comment by balaji-sivasakthi** [comment]
Basically, 'Try Free' works with authentication, and it has already been implemented. The only thing that needs to be done is to change the navigation path to the editor page.
