### ISSUE TITLE
Home Page is not Responsive

### ISSUE THREAD

**Issue by crocmons** [amanjaiman1/Product_3D#244]
### Describe the bug

Home Page is not Responsive for small devices..Please Assign this task to me as a GSSOC23 contributor.

### Expected behaviour

responsive for all devices

### Screenshots

![Screenshot (385)](https://github.com/amanjaiman1/Product_3D/assets/106610322/651e00c7-b7bf-4ce5-943f-28cd3f3b3bd4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
GoAhead !
