### ISSUE TITLE
Implement lazy loading to the pages

### ISSUE THREAD

**Issue by Avinash905** [amanjaiman1/Product_3D#245]
### Description

Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of resources until they are needed.

The benefits of lazy loading include:

- Reduced initial load time
- Improved user experience
- More responsive website

### Describe the solution you'd like

I would like to add lazy loading to the pages of the website to reduce the initial load time of a page, which can improve the user experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by amanjaiman1** [comment]
Good choice, Do it and let me know in how much time you can complete this

**Comment by Avinash905** [comment]
I will complete it by today. Can you add **GSSOC'23** and **level** labels too?

**Comment by amanjaiman1** [comment]
I will do it after the completion

**Comment by Avinash905** [comment]
Ok, thank you
