### ISSUE TITLE
Random Content in the Testimonial/Review Section

### ISSUE THREAD

**Issue by abhi03ruchi** [amanjaiman1/Product_3D#246]
### Describe the bug

The Testimonial/Review Section contains some random content. I would change the heading and the content inside so that it looks relevant to the project application.

### Expected behaviour

-

### Screenshots

<img width="530" alt="Screenshot 2023-06-05 at 4 24 52 AM" src="https://github.com/amanjaiman1/Product_3D/assets/105661636/4408277b-214c-4a2d-a3d8-455502c7a5fc">

### Additional context

Plz assign this task to me under gssoc'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
This title shouldn't needed @abhi03ruchi , but you can design the cards and their sliding animations in tailwindcss or normal css
or whatever you want to choose , do let me inform.

**Comment by amanjaiman1** [comment]
should i close this or you wanna work on ? @abhi03ruchi

**Comment by abhi03ruchi** [comment]
I will work on it.

**Comment by Nishitbaria** [comment]
@amanjaiman1 I want to work on it and I have already created many issues for testonimal

**Comment by Nishitbaria** [comment]
@amanjaiman1 Please Assign me and I can also give demo @balaji-sivasakthi

**Comment by balaji-sivasakthi** [comment]
@abhi03ruchi Are you still working?

**Comment by Nishitbaria** [comment]
@balaji-sivasakthi I am Working and make PR Today
