### ISSUE TITLE
Enhancing the Features Section of the site

### ISSUE THREAD

**Issue by abhi03ruchi** [amanjaiman1/Product_3D#247]
### Is your feature request related to a problem? Please describe.

I would like to improve the card design of the Features section. I would add 3 flip cards with feature name, which show feature details on hover. 

### Describe the solution you'd like

I would customize the card UI  based on the theme of the website.

https://github.com/amanjaiman1/Product_3D/assets/105661636/91242944-c734-4448-bea5-e043dff7aadb

### Describe alternatives you've considered

--

### Additional context

Plz assign this task to me under gssoc'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Good, go ahead 👍🏻

**Comment by Nishitbaria** [comment]
@amanjaiman1 I want to work on this issue

**Comment by amanjaiman1** [comment]
Please dont create the issues if you dont have the time to contribute.
Atleast save our time
