### ISSUE TITLE
Redesign the FAQ Page

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [amanjaiman1/Product_3D#252]
### Is your feature request related to a problem? Please describe.

At present FAQ's page is not looking nice and in Accordion one content bar is always opened by default.

### Describe the solution you'd like

I would like to redesign the FAQ'S page.
could you please assign this to me under Gssoc'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maitri-vv** [comment]
Hey! I would also love to work on this under GSSOC. I have enhancement of the issue of toggling.
Issue description: The FAQ questions currently there is not closing once it is viewed by user. Toggling out is not enabled to True. I will like to enhance this feature. I am raising a PR, please look over. Thanks :)
