### ISSUE TITLE
Docker automation for quick deployment

### ISSUE THREAD

**Issue by SwastikGorai** [amanjaiman1/Product_3D#253]
### Is your feature request related to a problem? Please describe.

The project does not have a action script to dockerize the project .

### Describe the solution you'd like

Create a dockerizing script so that whenever a PR is merged in a branch, the script will run and make a container for the project for quick deployment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Working or not?

**Comment by SwastikGorai** [comment]
Yes sir. Almost done.

**Comment by TripleteSumit** [comment]
Hey @SwastikGorai  Are you working on it. If not can I do it.

**Comment by SwastikGorai** [comment]
Okay, you can do it.

**Comment by TripleteSumit** [comment]
Ok @SwastikGorai
@amanjaiman1 Can you please assign me under GSSOC`23? can you please label this problem as well according to the GSSOC`23 criteria.
