### ISSUE TITLE
Footer links not functional

### ISSUE THREAD

**Issue by Avinash905** [amanjaiman1/Product_3D#256]
### Describe the bug

Some **Footer** links that are not added can be replaced with '**/**' home route and other routes that are added but are not working because they are present in a **li** tag due to which they are not redirecting. I would add a Link tag for them.

### Expected behaviour

On clicking on the links they should redirect to the corresponding page.

### Screenshots

![Screenshot (457)](https://github.com/amanjaiman1/Product_3D/assets/56786344/e62910b4-c669-4660-935f-9fe9ad4988dd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by amanjaiman1** [comment]
We will do this after the completions of pages so please wait

**Comment by Avinash905** [comment]
Ok

**Comment by amanjaiman1** [comment]
Hey @Avinash905 , i need to talk to you on Discord please reply ASAP!
