### ISSUE TITLE
Fix Text in Landing Page

### ISSUE THREAD

**Issue by Sriparno08** [amanjaiman1/Product_3D#269]
### Describe the bug

There is a typo in the landing page.

In this sentence:

> Go Through Reviews Of Previews Students To Make An Informed Decision

The 'Previous' word is spelt wrong.

### Expected behaviour

The sentence needs to be changed to:

> Go Through Reviews Of Previous Students To Make An Informed Decision

### Screenshots

![Screenshot 2023-06-10 202458](https://github.com/amanjaiman1/Product_3D/assets/89148144/c9c29aad-2e85-487a-a0fd-9d22ea56d7eb)

### Additional context

I would like to work on this as part of GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
Change this text to - Go Through Reviews Of Our Previous Clients To
