### ISSUE TITLE
Logo not aligned 

### ISSUE THREAD

**Issue by Abhinavcode13** [amanjaiman1/Product_3D#272]
### Is your feature request related to a problem? Please describe.

The issue is explained in the ss , i want to align this

### Describe the solution you'd like

Nothing

### Additional context

![image](https://github.com/amanjaiman1/Product_3D/assets/126642111/6402008b-a6a2-4b6a-bdd2-92419ed28a2f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
We have to change the logo buddy 
If you have any suggestion then please reply

**Comment by Abhinavcode13** [comment]
@amanjaiman1 I can work on the logo part, would that work?

**Comment by amanjaiman1** [comment]
Ohk go ahead
