### ISSUE TITLE
Issue: Blue Line Appearing in the Middle of the Text 

### ISSUE THREAD

**Issue by sudip57** [amanjaiman1/Product_3D#287]
### Describe the bug

I have encountered a problem on the website where a blue line is appearing in the middle of the text in the smaller screens.

### Expected behaviour

The text should be displayed without any visual artifacts such as the blue line.

### Screenshots

![Screenshot 2023-06-14 102510](https://github.com/amanjaiman1/Product_3D/assets/79646606/82d6ca14-b270-4d84-8399-4c4ac940d5f4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amanjaiman1** [comment]
I think this problem is seen after i merged a PR named footer links made functional , you check that first please

**Comment by sudip57** [comment]
![Screenshot 2023-06-14 232609](https://github.com/amanjaiman1/Product_3D/assets/79646606/a1a4d891-685a-41a1-9822-02a1c5e9a02b)
This footer is creating blue line not only in small screen but in all screen sizes.

**Comment by sudip57** [comment]
The issue has been resolved by another contributor before I had the opportunity to start working on it.
