### ISSUE TITLE
Bottons are not responding properly ex: "Goback" botton it will go back but background is not changed.

### ISSUE THREAD

**Issue by JeevarajBoomi** [amanjaiman1/Product_3D#3]
I'm GSSoC 23 Contributor. Can you Assign me to fix that.

**Comment by amanjaiman1** [comment]
Bro i cant understand the new changes you want to make it, can you please elaborate this?

**Comment by JeevarajBoomi** [comment]
https://github.com/amanjaiman1/Product_3D/assets/91022327/ff516319-b6f1-46e4-b5a0-f19184572bdd

👆This is the problem I was said.

**Comment by amanjaiman1** [comment]
Ohk got it , 
but firstly i want to inform you , 3D models required hardware acceleration and looking on that , your device is not rendering properly.
And secondly you are right the image is not removed in the mobile version , now i'm assigning you if you can do this.
