### ISSUE TITLE
Redesigning Landing Page for Improved UX

### ISSUE THREAD

**Issue by kapoorsaumitra** [amanjaiman1/Product_3D#30]
**Description:**
The current landing page of our website requires a redesign to enhance the user experience and improve overall conversion rates. The existing design may not effectively communicate our key messages and may not be visually appealing or user-friendly.

**Goals:**
- Create a visually appealing and modern design that aligns with our brand identity.
- Optimize the landing page layout to highlight key features and benefits.
- Improve the overall user experience to increase user engagement and conversion rates.
- Ensure responsiveness across different devices and screen sizes.

**Comment by aasthaaaa7** [comment]
please assign this issue to me

**Comment by Pujyalakshmi** [comment]
I will make a attractive UI for the home page. Please assign this issue to me.

**Comment by amanjaiman1** [comment]
Go ahead guys

**Comment by amanjaiman1** [comment]
Who is seriousely working on this issue ? 
See i have to assign one of you according to rules but i assigned you all three , now let me know who is completing and i have to set a timeline through which you have to complete your contribution.
otherwise sorry guys i have to unassign you

@Pujyalakshmi @aasthaaaa7 @kapoorsaumitra

**Comment by aasthaaaa7** [comment]
i am working on this issue

**Comment by aasthaaaa7** [comment]
@amanjaiman1 below is the link and ss of the design. Kindly suggest the required changes if any.

![Desktop - 1](https://github.com/amanjaiman1/Product_3D/assets/97506205/5467c48d-ad88-499c-a8b0-558997c867fd)

https://www.figma.com/file/BIEHHpz5aZewBGr2fv1aHg/GSSOC?type=design&node-id=7%3A2&t=YICbP2ttOd90ezI5-1

**Comment by amanjaiman1** [comment]
So good, you can make this one 
I appreciate your working ability @aasthaaaa7

**Comment by aasthaaaa7** [comment]
can you tell how can i submit this design in the repo

**Comment by amanjaiman1** [comment]
Please if you have time , DM on discord
I will be there to help out you

**Comment by aasthaaaa7** [comment]
ok

**Comment by MohamedMafaz** [comment]
Hey @amanjaiman1 
I am UI/UX Designer. Am I need to create UI Design for any page?

**Comment by amanjaiman1** [comment]
Yes you can , see first we have a landing page then a home page which is currently showing

**Comment by amanjaiman1** [comment]
Bro check the Design.md file and according to it , think and implement like our website is about 3D tshirt designer so adding such graphics etc etc 
Else if you need any help then please let me know

**Comment by amanjaiman1** [comment]
Please do connect me on Discord
GitHub comment is not good for discussion
