### ISSUE TITLE
Typewriter effect on main heading

### ISSUE THREAD

**Issue by Anshika-Jain02** [amanjaiman1/Product_3D#300]
*We can add a typewriter effect in the below heading to give a dynamic effect and to improve the visual appearance of the overall website.*

![image](https://github.com/amanjaiman1/Product_3D/assets/104912087/0f861b7d-ca4f-4dd7-8e41-0313bff10d96)

@amanjaiman1 Please assign me this issue under gssoc'23

**Comment by khadar1020** [comment]
please assign me this issue @amanjaiman1
