### ISSUE TITLE
Add the prettier linter workflow 

### ISSUE THREAD

**Issue by metabiswadeep** [amanjaiman1/Product_3D#313]
### Is your feature request related to a problem? Please describe.

As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using the prettier linter in GitHub actions.

### Describe the solution you'd like

Add the prettier linter to ensure proper and uniform linting of the codebase. 

I would like to work on this as a part of GSSoC 23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
#73

**Comment by metabiswadeep** [comment]
> (Prettier) #73 

No relevant PR has been made for that issue even though it had been opened 28 days ago, and it was also closed.

**Comment by balaji-sivasakthi** [comment]
It was not a duplicate issue and i make a note of it and that is basically created for codebase.
