### ISSUE TITLE
[Backend]: Request for Data Model Creation for 3D T-Shirt Design Project API

### ISSUE THREAD

**Issue by balaji-sivasakthi** [amanjaiman1/Product_3D#32]
## Description

We are facing challenges due to the absence of a proper data model for our API. This issue is impacting our ability to efficiently manage and ship products to our customers. I would like to request the creation of a data model for our API.

### Problem
Our project revolves around providing users with a platform to customize and order 3D-printed t-shirts. However, without a well-defined data model, we face difficulties in organizing, manipulating, and retrieving essential information such as design specifications, customer details, and shipping requirements.

### Proposed Solution
To address this issue, we need a data model that encompasses the following key entities:

- T-Shirt: Represents the customizable t-shirt object.
  - T-Shirt ID: Unique identifier for each t-shirt.
  - T-Shirt Design: Stores the design details and customization options.
  - Size: Tracks the selected size for each t-shirt.
  - Color: Manages the chosen color for the t-shirt.

- Customer: Stores customer information for order management and tracking.
  - Customer ID: Unique identifier for each customer.
  - Name: Captures the customer's name.
  - Address: Stores the shipping address.
  - Contact Details: Tracks the customer's contact information.

- Order: Represents a placed order for a t-shirt.
  - Order ID: Unique identifier for each order.
  - T-Shirt ID: References the chosen t-shirt.
  - Customer ID: References the customer who placed the order.
  - Quantity: Stores the number of t-shirts in the order.
  - Order Status: Tracks the current status of the order (e.g., processing, shipped, delivered).

### Benefits
Implementing a proper data model for our API will offer several benefits, including:

- Streamlined order management: With a well-structured data model, we can efficiently track and manage orders throughout the fulfillment process.
- Enhanced customization options: A data model will enable us to store and retrieve detailed design specifications, allowing customers to easily customize their t-shirts.
- Improved shipping processes: By incorporating shipping details into the data model, we can seamlessly manage shipping requirements and track delivery statuses.

I invite all team members to provide input and suggestions for the proposed data model. Let's work together to ensure a smooth and successful implementation that will significantly improve our project's efficiency and customer satisfaction.

I would like to work under **GSSOC'23** , Please assign this issue me

**Comment by amanjaiman1** [comment]
I respect your ultimate presence to the project workflow and your idea 
But I think if we can implement as you want then it will convert the whole website into eCommerce web i think

And i want to ask here how much time it will take for completion..?

**Comment by balaji-sivasakthi** [comment]
@amanjaiman1 Thank you for your kind words and acknowledging my presence in the project workflow. I appreciate your consideration of my idea. I understand your concern about the potential impact of implementing it on the website. In the readme.md file, you mentioned that once the user is satisfied with the design, they can place an order for the t-shirt. Based on that, I have created the model and I will need 1 or 2 days to complete it.

I have completed the simple diagrammatic data model. Please, I need your suggestions on anything that needs to be changed for our project.

![3d Product (1)](https://github.com/amanjaiman1/Product_3D/assets/65065614/47681194-ecc4-4c13-ab4d-0f280f95cb55)

**Comment by balaji-sivasakthi** [comment]
@amanjaiman1 I would like to work under GSSOC'23 , Please assign this issue me

**Comment by amanjaiman1** [comment]
I think you are so dedicated to the work, and i respect your gratitude so let begin this war 😉
