### ISSUE TITLE
Make a button Mic on AiPicker file which Recognised Speech to text instead of writing a prompt

### ISSUE THREAD

**Issue by creator79** [amanjaiman1/Product_3D#33]
Description goes

The "Mic on AiPicker" button is a feature that allows users to utilize speech recognition technology to convert spoken words into text. Instead of manually typing a prompt, users can simply click the Mic button and speak their input, which will be transcribed into text automatically. This feature enhances user convenience and efficiency by providing an alternative input method. By integrating speech-to-text functionality, users can enjoy a more streamlined and intuitive experience when interacting with the AiPicker file.

**Comment by creator79** [comment]
@amanjaiman1 please assign me this issue under a gssoc i

**Comment by amanjaiman1** [comment]
sounds extremely good, then give a start

**Comment by creator79** [comment]
@amanjaiman1 thanks for assigned me i will start work on it asap

**Comment by SurajPratap10** [comment]
Hey, @amanjaiman1,  I am assigned as your `MENTOR` so do connect with me on LINKEDIN , I tried visiting your Linkedin profile via your GitHub but it's not working..

**Comment by amanjaiman1** [comment]
> Hey, @amanjaiman1, I am assigned as your `MENTOR` so do connect with me on LINKEDIN , I tried visiting your Linkedin profile via your GitHub but it's not working..

I already sent you the connect request , do connect with me please and sir one thing i have made a proper discussion for the mentors so you can connect with all there.
Thanks

**Comment by SurajPratap10** [comment]
I haven't received any connect @amanjaiman1
