### ISSUE TITLE
Add CodeQL Workflow 

### ISSUE THREAD

**Issue by abhinav-m22** [amanjaiman1/Product_3D#336]
Although the repository has javascript code, it lacks workflow for code inspection.
The codeql.yml workflow file will be added by me to automate security checks.
CodeQL is a code analysis tool, to find vulnerabilities in programs. The code will be examined, and the results will be presented as code scanning alerts. Every push, commit, and pull request that uses GitHub actions will have it enabled.

I want to work on this issue under GSSoC'23

**Comment by abhinav-m22** [comment]
@amanjaiman1 Please assign me the issue

**Comment by amanjaiman1** [comment]
@balaji-sivasakthi  Please check this

**Comment by abhinav-m22** [comment]
So should I start working on it?

**Comment by balaji-sivasakthi** [comment]
Yes, you can start working on it.
