### ISSUE TITLE
Work on Customizer page

### ISSUE THREAD

**Issue by PatilHarshh** [amanjaiman1/Product_3D#343]
### Is your feature request related to a problem? Please describe.

adding of file section

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@amanjaiman1  I would like to work on this issue ,I can create pull request for this issue in 1 day to implement customizer, as  i have already worked with canvas .

**Comment by PatilHarshh** [comment]
> @amanjaiman1 I would like to work on this issue ,I can create pull request for this issue in 1 day to implement customizer, as i have already worked with canvas .

This is issue is not for implementing Canvas @Nishitbaria

**Comment by Nishitbaria** [comment]
> 

I am not impementing canvas ,I was just saying I have worked with canvas,So i can implement customizer page which is not working,So please assign me this issuemi will resolve it asap
