### ISSUE TITLE
[BUG] : Inconsistencies in font size, image placement, and padding across the pages

### ISSUE THREAD

**Issue by balaji-sivasakthi** [amanjaiman1/Product_3D#350]
#### Font Size: 
- Different pages exhibit varying font sizes, making it difficult for users to read and navigate the content consistently.

#### Image Placement:
-  Images on different pages are positioned inconsistently, with some centered, while others aligned to the left or right. This disrupts the visual flow and overall coherence of the project.

####  Padding:
- The padding between elements (e.g., text blocks, images, UI components) is not uniform. Some pages have excessive padding, resulting in wasted space, while others lack sufficient padding, causing elements to appear cramped and overlapping.

####  Font Size:
-  All pages should utilize the same font size to ensure readability and a cohesive user experience.

####  Image Placement:
-  Images should be consistently positioned across pages, adhering to a predefined alignment scheme to maintain visual coherence.

#### Padding: 
- There should be a consistent and appropriate amount of padding between elements on all pages, allowing for proper spacing and organization of content.

### Screenshots

![image](https://github.com/amanjaiman1/Product_3D/assets/65065614/66cb180a-c9cd-40e6-9bdc-3a1cbc90c6c6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
@Vatsalmadhur want to work on this?

**Comment by creator79** [comment]
@balaji-sivasakthi  I will do that @amanjaiman1 please re-assign to me

**Comment by balaji-sivasakthi** [comment]
Ok
