### ISSUE TITLE
Changing the UI of the "/tshirt-customisation#" section

### ISSUE THREAD

**Issue by Vatsalmadhur** [amanjaiman1/Product_3D#364]
### Is your feature request related to a problem? Please describe.

The entire section is not vertically centred. Its more towards the bottom. I would like to fix this. Here is a screenshot attached.
<img width="1440" alt="Screenshot 2023-06-24 at 9 48 04 PM" src="https://github.com/amanjaiman1/Product_3D/assets/107473447/caae4bd4-39be-44bd-bb22-d23693abc56f">

### Describe the solution you'd like

I would like to centrally align  this page's content to make it look clean and professional.

### Describe alternatives you've considered

I am also thinking of adding a glassmorphism effect to the background, to make it look appealing as well as simple at the same time.

### Additional context

I request you to assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
PLease leave this issue for now
