### ISSUE TITLE
LOGO Overflow

### ISSUE THREAD

**Issue by Vatsalmadhur** [amanjaiman1/Product_3D#365]
### Describe the bug

The Logo of the webpage overflows when the height of navbar changes for mobile view. I would like to fix it. Here is screenshot for the same.
<img width="1440" alt="Screenshot 2023-06-24 at 9 57 04 PM" src="https://github.com/amanjaiman1/Product_3D/assets/107473447/cd668275-57c9-42ec-9616-f35a559b7794">

### Expected behaviour

The logo will be perfectly aligned to fit all screen sizes.

### Screenshots

<img width="1440" alt="Screenshot 2023-06-24 at 9 57 04 PM" src="https://github.com/amanjaiman1/Product_3D/assets/107473447/3fba4069-de43-4450-b2e7-055a7b44ab04">

### Additional context

I request you to assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Vatsalmadhur** [comment]
Please assign me this issue

**Comment by khadar1020** [comment]
please assign me this issue @amanjaiman1
