### ISSUE TITLE
Padding issue in "Getting Started " page

### ISSUE THREAD

**Issue by Vatsalmadhur** [amanjaiman1/Product_3D#366]
### Describe the bug

This page requires padding from the left and right to make the text more centralised.
<img width="1440" alt="Screenshot 2023-06-24 at 10 17 01 PM" src="https://github.com/amanjaiman1/Product_3D/assets/107473447/fddebc89-5b30-4218-8e23-5123835fcaf3">

### Expected behaviour

Providing effective padding will enhance the overall readability of the page.

### Additional context

I request to assign me this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
@amanjaiman1    #350  duplicate issue

**Comment by balaji-sivasakthi** [comment]
I'm currently working on it.

**Comment by amanjaiman1** [comment]
> @Vatsalmadhur I'm currently working on it.

Closing
