### ISSUE TITLE
Add sliding effects to components of Blog page

### ISSUE THREAD

**Issue by abhinav-m22** [amanjaiman1/Product_3D#368]
### Is your feature request related to a problem? Please describe.

The blog page looks more as a static webpage unlike the home page. 

I would redesign the whole page!

I would like to add some sliding animations such as fade-left, fade-right or pop-up, etc. in order to make the webpage look dynamic and in consistent to the home page.

### Describe the solution you'd like

Adding CSS transitions by an external library would do this job. The webpage will be more interactive and UI/UX will be improved as it looks more static now.
Also I will add more blog articles.

### Additional context

I would like to work on this task.
Please assign me the issue under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by abhinav-m22** [comment]
@amanjaiman1 @balaji-sivasakthi 
Please assign me the issue

**Comment by balaji-sivasakthi** [comment]
Come here https://discord.gg/ajWsFy54

**Comment by balaji-sivasakthi** [comment]
#490
