### ISSUE TITLE
Enhance Ui of the reviews section.

### ISSUE THREAD

**Issue by Pragati-3003** [amanjaiman1/Product_3D#370]
### Is your feature request related to a problem? Please describe.

i would like to change the ui of the reviews section to make it more attractive .
So,please assign this issue to me under gssoc'23.
![image](https://github.com/amanjaiman1/Product_3D/assets/132778037/ac457658-d91d-4310-acd1-f711e8fd581d)

### Describe the solution you'd like

I would like to add some cool effects and box-shadows.
Also would like to adjust the existing css properties.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
WHAT you gonna change in UI , please tell me @Pragati-3003
