### ISSUE TITLE
newsletter link in the footer should direct to the newsletter section

### ISSUE THREAD

**Issue by Illaf** [amanjaiman1/Product_3D#376]
### Is your feature request related to a problem? Please describe.

On clicking the newsletter link, it directs to the home page which after manually scrolling shows the newsletter section

### Describe the solution you'd like

On clicking the newsletter link, it should directly open the newsletter page rather than directing to the home page which lefts the user clueless.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Do we have the page?
Done with some research or directly made the issues
