### ISSUE TITLE
The Blog section heading and cards issue

### ISSUE THREAD

**Issue by k-deepak04** [amanjaiman1/Product_3D#385]
### Describe the bug

in the blogs section heading is covered by cards also cards are overlapping on one above the other

### Expected behaviour

there should be some space so that things do not club together and are visually appealing

### Screenshots

our articles is covered
![image](https://github.com/amanjaiman1/Product_3D/assets/96341431/279db85f-b868-403e-882e-ace74eaccd49)

one above other
![image](https://github.com/amanjaiman1/Product_3D/assets/96341431/6cb662b7-1506-4e9f-abf8-470c697d96d3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by k-deepak04** [comment]
@amanjaiman1 i want to resolve this issue and make the things look good and responsive
Also the invalid tag is automatically coming

**Comment by amanjaiman1** [comment]
First complete your two other issues then i will assign this to you.

**Comment by k-deepak04** [comment]
sure
