### ISSUE TITLE
Add the closing function to (colour custom ,file , Ai)buttons .

### ISSUE THREAD

**Issue by JeevarajBoomi** [amanjaiman1/Product_3D#4]

**Comment by JeevarajBoomi** [comment]
![IMG_20230520_085602.jpg](https://github.com/amanjaiman1/Product_3D/assets/91022327/49b57fea-fa20-45da-b0ad-1dca9116e113)

Issue in these buttons. You can click to open that slide view bar, move to another view but the issue is you can't close slide view bar.

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by amanjaiman1** [comment]
Yeah Guys , great to know you find this issue.

**Comment by amanjaiman1** [comment]
and @SakshiShah29 , what will be your contribution area , i just want to know.

**Comment by JeevarajBoomi** [comment]
I'm front end developer. I will fix that bug

**Comment by SakshiShah29** [comment]
> and @SakshiShah29 , what will be your contribution area , i just want to know.

I am a Frontend Dev as well, I can contribute in customizing the button and solving the bug
