### ISSUE TITLE
Aligning Cards in Customizer Page

### ISSUE THREAD

**Issue by parasss19** [amanjaiman1/Product_3D#406]
## Current
- Cards are not aligned properly 

https://github.com/amanjaiman1/Product_3D/assets/101205226/2eca6fd9-1b1d-4c26-a74d-a389383e642c

### Expected behaviour

- They should be properly aligned and looks better 

https://github.com/amanjaiman1/Product_3D/assets/101205226/e626af7a-0b45-49ba-aff0-a97ef2460873

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Do with the left part alignment also
