### ISSUE TITLE
double click hover effect move

### ISSUE THREAD

**Issue by dheeraj1129** [amanjaiman1/Product_3D#408]
### Describe the bug

when double click on the recent design button the hover effect moves to the favorite button and vice versa.

https://github.com/amanjaiman1/Product_3D/assets/72201773/04296b19-e91e-4c26-8948-7780c6d3ec56

### Expected behaviour

make fixed hover effecta 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
@dheeraj1129  Good catch, ymm kick off.

**Comment by balaji-sivasakthi** [comment]
Just use the useLocation() hooks from react-router-dom

*component path*
`..Product_3D\client\src\components\CustomizerSidebar\index.jsx`

**Comment by amanjaiman1** [comment]
> @dheeraj1129
> 
> Just use the useLocation() hooks from react-router-dom
> 
> * right now, we are using useState to handle the sidebar items
> * You've to fix the style by using the current path and make a condition for the sidebar items for the styles
> 
> _component path_ `..Product_3D\client\src\components\CustomizerSidebar\index.jsx`

Would i assign or not @balaji-sivasakthi ?

**Comment by balaji-sivasakthi** [comment]
Yeah assign to him

**Comment by amanjaiman1** [comment]
Want to work on this or not?

**Comment by dheeraj1129** [comment]
I am working on it
