### ISSUE TITLE
Add a Designs Slider on Homepage

### ISSUE THREAD

**Issue by Tisha6661** [amanjaiman1/Product_3D#414]
### Is your feature request related to a problem? Please describe.

The homepage is expected to be eye catchy to the users and show how creative you can get with this webiste.

### Describe the solution you'd like

I would like to add a carousel to show the design that have been created, and how much creative they are. It attracts the users to try designing T-shirt for themselves too.

### Describe alternatives you've considered

We can show off the best features of the site in it.

### Additional context

Please let me add this enhancement to the site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Please join our Discord  and share what changes you wanna  do.

**Comment by balaji-sivasakthi** [comment]
@Tisha6661  https://discord.gg/SjSmtxxG

**Comment by amanjaiman1** [comment]
Dont create issue if you are not available to do so
