### ISSUE TITLE
Making Customizer Page Responsive 

### ISSUE THREAD

**Issue by PatilHarshh** [amanjaiman1/Product_3D#419]
### Is your feature request related to a problem? Please describe.

Resposnive of Color page and design page @amanjaiman1 

### Describe the solution you'd like

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
First share the issue on Discord with @balaji-sivasakthi

**Comment by PatilHarshh** [comment]
@amanjaiman1 check group
