### ISSUE TITLE
 Image/Logo Upload, Download image

### ISSUE THREAD

**Issue by MagdyNasr41** [amanjaiman1/Product_3D#42]
I want to create api to upload image into a database so that user can apply the designs on it. I plan to create a simple mongodb schema so that I insert the image url in it. also I plan to create a validation layer and class for customized error handling. "under gssoc"

**Comment by amanjaiman1** [comment]
Can you please elaborate this issue more?

**Comment by amanjaiman1** [comment]
Ohk go Ahead

**Comment by yashraj-exe** [comment]
can you also assign this issue to me if @MagdyNasr41 dont have any problem. we can work together on this issue

**Comment by amanjaiman1** [comment]
> can you also assign this issue to me if @MagdyNasr41 dont have any problem. we can work together on this issue

i think you are already enrolled in other issues na?

**Comment by yashraj-exe** [comment]
yes hai issue tackle kr shakte he kya 😅
