### ISSUE TITLE
[Bug] Fix responsiveness 3d model in customiser page

### ISSUE THREAD

**Issue by creator79** [amanjaiman1/Product_3D#422]
### Describe the bug

The shirt will overlapping overall design 

### Expected behaviour

Using React fiber to make it responsive
Optimised the server side rendering for flow of loading model on low end device 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
@creator79 At the same time remove the navbar and footer in editor, We don't need it in editor page.

**Comment by khadar1020** [comment]
please assign me this issue @balaji-sivasakthi
