### ISSUE TITLE
Button Design

### ISSUE THREAD

**Issue by parasss19** [amanjaiman1/Product_3D#427]
### Describe the bug

- Design of buttons are different 

### Expected behaviour

- They should be same for the whole website

### Screenshots

<img width="927" alt="Screenshot 2023-07-09 130834" src="https://github.com/amanjaiman1/Product_3D/assets/101205226/8f3d31d5-b751-4cad-a668-61052fe74cf2">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
@parasss19 Did you work on this issue?

**Comment by khadar1020** [comment]
please assign me this issue @amanjaiman1
