### ISSUE TITLE
BUG Download button doesn't working

### ISSUE THREAD

**Issue by creator79** [amanjaiman1/Product_3D#43]
I want to fix this issue i have fix this in my local and make it label under gsssoc

**Comment by amanjaiman1** [comment]
Thanks , you are catching logical issues.
I appreciate that energy

**Comment by creator79** [comment]
@amanjaiman1 please make a label under GSSOC

**Comment by creator79** [comment]
@amanjaiman1 i created a pull request its work on my local perfectly but it seems to be conflict in creating pr for Issue no 43 can you please help me out these

**Comment by amanjaiman1** [comment]
Can you please reach out to mentor?
I think they will help you in more efficient way
