### ISSUE TITLE
Placing of the 3d model.

### ISSUE THREAD

**Issue by PiyushK79** [amanjaiman1/Product_3D#440]
### Describe the bug

The 3d model displayed of the tshirt is way out of its bounds.

### Expected behaviour

The 3d tshirt needs to stick inside the blue section in its confined space.

### Screenshots

![image](https://github.com/amanjaiman1/Product_3D/assets/100259650/a337db4d-fc16-4255-bd16-a2917a090444)

### Additional context

Also the size of the tshirt needs to be full so we can also remove the functionality of increasing and decreasing the size of the tshirt.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushK79** [comment]
@amanjaiman1  Please assign this issue to me under Gssoc23.

**Comment by amanjaiman1** [comment]
@balaji-sivasakthi and @creator79 , Please look into this.

**Comment by creator79** [comment]
@PiyushK79 tell me how can you do that in detail

**Comment by PiyushK79** [comment]
I think someone has messed with the placing of the model that's it. I would need to correct the placing of the model by giving it some constraints. 
Also I would like to remove the zoom in and out feature as the model needs to be maxed out so that user will be able to see his changes clearly.

**Comment by creator79** [comment]
@PiyushK79 No don't change any Features
1 Make container model fixed
2 responsive the model in small medium and large screen sizes
You just move the 3d model in top with respect to containers

**Comment by PiyushK79** [comment]
Alright I will fix the container size of the model.
Assign this issue to me so I can start working on it.

**Comment by creator79** [comment]
@PiyushK79 go ahead
