### ISSUE TITLE
Contributors Title not align

### ISSUE THREAD

**Issue by parasss19** [amanjaiman1/Product_3D#446]
### Describe the bug

- In contributor page the titles of contributor cards not aligned 

### Expected behaviour

- They should be aligned properly with the below text

## Original 
https://github.com/amanjaiman1/Product_3D/assets/101205226/f126e634-3c07-43ac-8dfe-b59d1861c57a

## Updated
https://github.com/amanjaiman1/Product_3D/assets/101205226/1ddfd06b-cda1-42f2-9ecd-e3ed3cd53818

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Make the Cards more better
