### ISSUE TITLE
Blog page 

### ISSUE THREAD

**Issue by BhartiNagpure** [amanjaiman1/Product_3D#454]
### Describe the bug

There is need to give proper styling to blog page articles card.

### Expected behaviour

It shows the text out of card container and also need to give margin padding.

### Screenshots

![Screenshot 2023-07-15 145113](https://github.com/amanjaiman1/Product_3D/assets/104631882/aa1341c5-9bc4-4b30-b063-3f2fd91668a1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Hey @BhartiNagpure , kindly contact me on Discord.

**Comment by BhartiNagpure** [comment]
> Hey @BhartiNagpure , kindly contact me on Discord.

I am sending request to you 
on discord

**Comment by senthil-k8s** [comment]
Hey @BhartiNagpure, are u still working on blog page

**Comment by BhartiNagpure** [comment]
Your not assigning me thats why I am waiting for your kindly reply.

**Comment by balaji-sivasakthi** [comment]
@BhartiNagpure kindly join on https://discord.gg/SBZVBTMJ

**Comment by balaji-sivasakthi** [comment]
#490
