### ISSUE TITLE
Inconsistent Button Design Across Website

### ISSUE THREAD

**Issue by senthil-k8s** [amanjaiman1/Product_3D#461]
### Is your feature request related to a problem? Please describe.

**Issue:** Inconsistent Button Design Across Website

### Description:
The buttons used across the website currently lack uniformity in terms of design, leading to an inconsistent user experience. This issue needs to be addressed to ensure a cohesive and visually pleasing interface throughout the website.

### Specifics:

The buttons on different pages of the website have varying styles, such as different colors, sizes, or shapes.
In some cases, buttons are missing hover or active states, resulting in a lack of visual feedback for users.
The typography used within buttons may also differ, including variations in font family, size, or weight.

### Expected Outcome:

We need to establish a consistent button design that aligns with the overall branding and enhances the website's user interface. By achieving a uniform button style, we can provide users with a visually coherent experience and improve usability.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by akanksha984** [comment]
Please assign this to me @amanjaiman1
