### ISSUE TITLE
Improvement of Login Page

### ISSUE THREAD

**Issue by prashanth772** [amanjaiman1/Product_3D#472]
### Is your feature request related to a problem? Please describe.

The login button is not properly placed and the sign up button

![image](https://github.com/amanjaiman1/Product_3D/assets/124067333/3195b697-094e-4767-b1d4-88e7de2b9360)

### Describe the solution you'd like

Fixing the buttons and improving the alignments.

### Additional context

Assign me this issue under GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Hii @prashanth772 , do you know firebase configuration for login and signup ?

**Comment by prashanth772** [comment]
@amanjaiman1 No, I just want to enhance the UI.

**Comment by amanjaiman1** [comment]
Ohk then Go for it
