### ISSUE TITLE
adding pre-existing logo design template options, adding  pre made contents of t-shirt design,  adding account creating features, adding wishlist options

### ISSUE THREAD

**Issue by AnujBhushanTiwari** [amanjaiman1/Product_3D#48]
1.Pre existing logo design template options can be added to the website that can help create designs much faster than uploading and creating logo
2. Adding pre made contents of t-shirt design so that user can view what types of designs can be made on this website.
3. Adding account creating features which will contain all the data of the user like username, email, phone number so that notifications can be sent.
4. Adding wishlist options to save the design data.
**I can add these features in the website .

**Comment by AnujBhushanTiwari** [comment]
@amanjaiman1 kindly give me approval for this project and I will immediately start working on it.

**Comment by amanjaiman1** [comment]
I hope you will do best out of best.

**Comment by AnujBhushanTiwari** [comment]
Thank you sir for the opportunity

**Comment by Akanksha038** [comment]
Hello @amanjaiman1 Sir,
I would like to be adding add pre-existing logo design template options, pre made contents of t-shirt design,  account creating features, and Wishlist options This will help to enhance the user experience.
Please assign me this issue. I would like to work on this issue under GSSOC'23. Please let me fix this issue #48.
