### ISSUE TITLE
Blogs page card Text overflow css Issue

### ISSUE THREAD

**Issue by biplavmz** [amanjaiman1/Product_3D#498]
### Describe the bug

go to the blogs tab and Blogs page card Text overflow css Issue

### Expected behaviour

Text should not be overflow
I'm a GSSoC'23 contributor please assign me this issue under gssoc label and level.

### Screenshots

<img width="518" alt="image" src="https://github.com/amanjaiman1/Product_3D/assets/68702055/00d1b652-fcb0-4c5e-a63c-473ce35e437a">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
Do it

**Comment by balaji-sivasakthi** [comment]
#490 Duplicate Issue
