### ISSUE TITLE
[GSSOC'23]  Tshirt competition

### ISSUE THREAD

**Issue by vivxsdb** [amanjaiman1/Product_3D#505]
### Is your feature request related to a problem? Please describe.

Actually I want to implement a T shirt competition where the users can participate actively helping in getting creative ideas on tshirt. and will also be implementing like and dislike feature to each tshirt

### Describe the solution you'd like

Actually I want to implement a T shirt competition where the users can participate actively helping in getting creative ideas on tshirt. and will also be implementing like and dislike feature to each tshirt

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
How do you implement it?

**Comment by vivxsdb** [comment]
I will creating a seperate window for it .you can just consider the above implementation  like a  fashion show competition

**Comment by balaji-sivasakthi** [comment]
I means technically

**Comment by vivxsdb** [comment]
Since your project is having a firebase storage so we will be implementing a seperate window for the competition section and after that a registeration form for registering into the contest and in the users database his tshirts design will be there so will in the users' database, his t-shirt designs will be stored, along with other relevant information such as their username, email, and likes received on each design. The competition section will feature a dedicated interface where users can browse through all the submitted t-shirt designs and a like and dislike button for the t-shirt

**Comment by vivxsdb** [comment]
Or if possible can I contact you in discord so that I can explain properly

**Comment by amanjaiman1** [comment]
@vivxsdb You are Vishnu?

**Comment by vivxsdb** [comment]
Yes I am Vishnu
