### ISSUE TITLE
[GSSOC'23] Different accessories

### ISSUE THREAD

**Issue by vivxsdb** [amanjaiman1/Product_3D#506]
### Is your feature request related to a problem? Please describe.

Actually I want to implement the different accessories desgin feature into your project . Can u please assgin me this issue under GSSOC'23

### Describe the solution you'd like

Actually I want to implement the different accessories desgin feature into your project . Can u please assgin me this issue under GSSOC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by balaji-sivasakthi** [comment]
Could you explain in detail?

**Comment by vivxsdb** [comment]
Like design of tie , pants , belts etc

**Comment by vivxsdb** [comment]
Actually implementing this will be a better choice I think so
