### ISSUE TITLE
FEAT: Improving some component for better visuals

### ISSUE THREAD

**Issue by Prashu-01** [amanjaiman1/Product_3D#514]
### Is your feature request related to a problem? Please describe.

Some of the components are not responsive for screen other than PC. Making it better like improvements required in some of the components like 

1. HeroUI of homepage 
![Screenshot 2023-07-23 020012](https://github.com/amanjaiman1/Product_3D/assets/107640576/8ffb9744-0c7a-42d1-9406-83f9a6351a15)

2. Contributor card text on hover in contributor section
![Screenshot 2023-07-23 020236](https://github.com/amanjaiman1/Product_3D/assets/107640576/a638be55-1ffb-4bb6-9705-e678cee541ce)

3. To big 'lets create' button for mobile view
![Screenshot 2023-07-23 021320](https://github.com/amanjaiman1/Product_3D/assets/107640576/6c546e03-ec22-4bfc-9bed-97ddb247c663)

### Describe the solution you'd like

Similar size div for both image and texts making the title bit large and bold
For contributors card highlighted name, all texts at center
Better size button of footer for mobile view

### Describe alternatives you've considered

Redesign the component so that it would fit better with the UI. 

### Additional context

Hey @amanjaiman1  should I make all the buttons in homepage similar or is it okay?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Prashu-01** [comment]
Hey @amanjaiman1 assign me this under GSSOC'23 so that I would start working on this.
Also I left my doubt in additional context please mark that

**Comment by balaji-sivasakthi** [comment]
@Prashu-01 Are you working on it?

**Comment by balaji-sivasakthi** [comment]
OK, complete it soon.

**Comment by Prashu-01** [comment]
Hey @balaji-sivasakthi , how to set the environment variables for the project?

Need help with this section :-

![Screenshot 2023-07-24 175302](https://github.com/amanjaiman1/Product_3D/assets/107640576/e70c519e-c511-467b-9469-8ca2407479cb)

**Comment by balaji-sivasakthi** [comment]
We have provided a Discord link in the readme file. Feel free to join us and ask any questions you may have.
