### ISSUE TITLE
FEAT: ADD PRETTIER TO VALIDATE CODE CONSISTENCY ✨

### ISSUE THREAD

**Issue by 0xabdulkhalid** [amanjaiman1/Product_3D#522]
## Description
- As our project continues to grow and attract more contributors, maintaining consistent code formatting becomes increasingly crucial for readability and collaboration. To address this, I propose integrating Prettier into our GitHub repository as a code formatting tool.
- In this case, the workflow is designed to trigger whenever a code change is pushed to the repository, this workflow automatically checks the codebase for proper formatting using Prettier. 
- With Prettier, we can ensure that all code contributions align with the established coding standards, reducing the burden on developers to manually maintain consistent formatting.

**Comment by 0xabdulkhalid** [comment]
Hey there @amanjaiman1, @balaji-sivasakthi 👋🏻

Please make sure to assign this issue to me as soon as possible so that i can proceed my progress regarding fixing this issue.

Thank you!

**Comment by balaji-sivasakthi** [comment]
@0xabdulkhalid  Thank you for your patience towards this project, and it's really appreciated. However, this issue is not needed as we already have a prettier pre-commit hook in our code base itself.
