### ISSUE TITLE
feat: export & import design file

### ISSUE THREAD

**Issue by balaji-sivasakthi** [amanjaiman1/Product_3D#530]
### Is your feature request related to a problem? Please describe.

The project currently lacks an efficient and user-friendly import and export functionality. This feature is essential for enabling users to easily transfer data in and out of the project, enhancing its usability and data management capabilities.

### Describe the solution you'd like

I would like to create functionality for serializing and deserializing the T-shirt design data for import and export features.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Thanks for your service , we will not meet u soon.
