### ISSUE TITLE
[DOCS] Discord's invite invalid

### ISSUE THREAD

**Issue by JefferMarcelino** [amanjaiman1/Product_3D#532]
### Description

I attempted to join the Discord server mentioned in the README.md, but unfortunately, the invite seems to be invalid. It appears to have expired or might have been revoked. As a result, I'm unable to access the Discord community associated with this repository.

### Screenshots

![image](https://github.com/amanjaiman1/Product_3D/assets/77571208/43cf88e4-a1f8-4e8b-8fba-0550b82cd9bf)

### Additional information

- Discord Server Invite: https://discord.com/invite/V48uzUSW
- Date/Time of Attempt: Monday 24 July, 19:23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
https://discord.gg/TrjKScjc @JefferMarcelino Here's the right link

**Comment by JefferMarcelino** [comment]
This link expires in 16 hours. Can you generate a link that has no expiration? @amanjaiman1 

![1690305619246](https://github.com/amanjaiman1/Product_3D/assets/77571208/7959b1c2-1bc4-4c67-ba71-b93dab728bc9)

**Comment by amanjaiman1** [comment]
So how can we do the permanent invite link?

**Comment by amanjaiman1** [comment]
@JefferMarcelino  Take this link 

https://discord.gg/JW9K58FBfs 
Now our server is a community server

**Comment by JefferMarcelino** [comment]
Thanks, @amanjaiman1! This is exactly what I needed.
