### ISSUE TITLE
feat: dark mode in customizer panel

### ISSUE THREAD

**Issue by balaji-sivasakthi** [amanjaiman1/Product_3D#562]
### Is your feature request related to a problem? Please describe.

Currently, the customizer panel does not offer any dark mode functionality. The UI remains in the default light mode regardless of the user's preference.

### Describe the solution you'd like

Plan and design the dark mode UI elements for the customizer panel. Consider factors like colour scheme, contrast, and readability in both light and dark modes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by creator79** [comment]
@balaji-sivasakthi  should i work on this issue
@amanjaiman1  please assigned me this issue
