### ISSUE TITLE
[FEAT]: Adding Contributors in HomePage

### ISSUE THREAD

**Issue by senthil-k8s** [amanjaiman1/Product_3D#569]
### Description:
Currently, the home page of the website lacks a section dedicated to acknowledging and displaying the contributors who have contributed to the project. It's essential to recognize their efforts and contributions, as it fosters a sense of community and gratitude within the project.

### Current Behavior:
As of now, the home page does not have any section or display mechanism to showcase the contributors' names. Consequently, the valuable contributions of individuals are not being highlighted, and there is a missed opportunity to express appreciation for their efforts.

### Expected Behavior:

The home page should include a dedicated section that lists the names or usernames of contributors who have actively participated in the project. Ideally, this section could be visually appealing and include links to their profiles or any relevant information about their contributions.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by creator79** [comment]
i want a worked on this issue @amanjaiman1  @senthil-k8s
