### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [amanjaiman1/Product_3D#6]
I want to add readme badges.Please assign this issue to me under GSSOC
![badges](https://github.com/amanjaiman1/Product_3D/assets/104543751/e550eec6-ab91-450c-8741-d5c0ca98364a)

**Comment by amanjaiman1** [comment]
Ok Do it ishita

**Comment by S-ishita** [comment]
hey @amanjaiman1 can i close this issue now..as it is completed now?

**Comment by amanjaiman1** [comment]
Yup
