### ISSUE TITLE
Adding Hover Effects to Buttons

### ISSUE THREAD

**Issue by AkanshaMundel** [amanjaiman1/Product_3D#61]
I have a suggestion to improve the user interface (UI) by incorporating hover effects and animations for buttons. By implementing these visual enhancements, we can provide a more engaging and interactive experience for users. The addition of hover effects can create a subtle yet noticeable response when users interact with buttons,

I would be thrilled to contribute to this and kindly request to be assigned this task under GSSOC'23

**Comment by amanjaiman1** [comment]
You can start now and best of luck for your contribution 🤠
