### ISSUE TITLE
Editor Content component close icon doesn't show in dark mode

### ISSUE THREAD

**Issue by SubhamB2003** [amanjaiman1/Product_3D#62]
In light mode, it can show
![image](https://github.com/amanjaiman1/Product_3D/assets/94003231/b9a0823c-122a-429a-9b12-3dc3a84ffcd0)

But in dark mode icon are not showing
![image](https://github.com/amanjaiman1/Product_3D/assets/94003231/500e3252-5aae-4a63-a6be-ca4387d80023)

I want to work on this issue under GSSOC23. Please assign it to me.

**Comment by amanjaiman1** [comment]
Ohk Go ahead
