### ISSUE TITLE
Accessible and Inclusive Design Recommendations 

### ISSUE THREAD

**Issue by soumizde** [amanjaiman1/Product_3D#63]
Concerns and Suggestions:

1. There seems to be no feedback for any button - they all feel very static. The click feedback needs to be established for buttons
2. The Go Back button is on the right side - It needs to be on the left for user accessibility 
3. The animations are quite fast and do not follow the base 300ms animation standard and is hard to reverse an action 
4. There needs to be a prompt or a feature explaining what button does what. Because even for a person like me, I did click random buttons to find out what each does and still ended up downloading the picture twice
5. A logo needs to be made - currently a Vite icon is being used and that should be removed. A favicon and a logo is required

**Comment by amanjaiman1** [comment]
I admire your thinking and one thing I want to add we are making navbar on home page so do enhance that doesn't create any problem for others 

you can start your contribution from now
Best of luck

**Comment by soumizde** [comment]
Thank you so much. I will surely try and add a nav bar and iterate over some designs

**Comment by soumizde** [comment]
Hey hi, so I just wanted to know what all do we plan for this website in the future. I will then be able to add the nav bars accordingly. I am currently thinking  Home, Theme, Customize are the only things that I see that can be added in the navigation bar. Anything else that you have in mind?

**Comment by amanjaiman1** [comment]
You can discuss this on Discord.
