### ISSUE TITLE
Complete website Width Issue [GSSoc'23]

### ISSUE THREAD

**Issue by Monilprajapati** [amanjaiman1/Product_3D#638]
### Describe the bug

The width of the website is not good. As you can see in this preview

Preview:

https://github.com/amanjaiman1/Product_3D/assets/99136041/c6b85d04-8b0a-496e-bfae-4194ba6ea2f1

### Expected behaviour

I will fix it and will make it more user friendly and device compatible.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
If you can fix this , do fast till mid night please
