### ISSUE TITLE
Review section cards with carousel functionality [GSsco'23]

### ISSUE THREAD

**Issue by Monilprajapati** [amanjaiman1/Product_3D#639]
### Is your feature request related to a problem? Please describe.

I will redesign that Review section and will add Review card with carousel functionality so that it will slide automatically and by the user also so that if user wants to slide by himself.

Right now :
![image](https://github.com/amanjaiman1/Product_3D/assets/99136041/95865cf6-dd25-4eaa-9e69-b20c73ef6981)

### Describe the solution you'd like

I will make it more user friendly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amanjaiman1** [comment]
Do complete this by midnight today if you want your deserving labels

**Comment by Monilprajapati** [comment]
Hey @amanjaiman1 Is this repo still active? So I can make the changes that I have mentioned in this issue now and raise the PR.
