### ISSUE TITLE
[BACKEND] Request for Backend Design using MVC Folder Structure

### ISSUE THREAD

**Issue by yashraj-exe** [amanjaiman1/Product_3D#68]
I would like to request the design and implementation of the backend architecture using the MVC (Model-View-Controller) folder structure for a MongoDB, Node.js, and Express project. This structure will help us organize our codebase and maintain a clear separation of concerns between different components of our application. This can include improved code, easier maintenance, scalability, and reusability and seperate business logic in controlers folder using OOPS

Example:

![Screenshot 2023-05-22 103554](https://github.com/amanjaiman1/Product_3D/assets/91207380/33ac73fe-f2d8-46c3-81ed-536f9368391a)

( I would like to work on this issue, please assign this issue to me under GSSoC'23. @amanjaiman1)

**Comment by amanjaiman1** [comment]
Bro i have merged your previous PR , and now I want to talk to you ASAP 
Comeon discord please
