### ISSUE TITLE
[GSSoC'23] Improving UI of uploading the file container

### ISSUE THREAD

**Issue by nishita2104** [amanjaiman1/Product_3D#71]
The UI of this container can be improved to make it readable and better understandable. For example the close button has to eb aligned properly and other similar minor modifications can be done. 

![image](https://github.com/amanjaiman1/Product_3D/assets/98174888/049e7d80-b030-418b-81a7-c46f434dc9b4)

**Comment by amanjaiman1** [comment]
Ohk Go ahead !
