### ISSUE TITLE
[chore]: Refactor Client Code for Improved Structure

### ISSUE THREAD

**Issue by balaji-sivasakthi** [amanjaiman1/Product_3D#74]
**Description:**
We need to refactor the client code to improve its structure and organization. The current codebase lacks a proper structure, making it difficult to understand and maintain. By refactoring the code, we aim to enhance readability, modularity, and scalability, ultimately improving the overall quality of the project.

**Comment by oshinsaraf** [comment]
Can i be assigned this issue under GSSOC'23?
