### ISSUE TITLE
UI Improvement Suggestions

### ISSUE THREAD

**Issue by soumizde** [amanjaiman1/Product_3D#77]
I want to change the theme button and place an icon in that - preferably a moon for the night/dark mode and a sun for the white mode.

I think that it will definitely add to the UI and make it easier for the users to understand what the "theme" is.

**Comment by amanjaiman1** [comment]
Go ahead ⭐

**Comment by khushiminda** [comment]
i am a UI/UX designer
pls give me a chance to make yourr web page 
I think that it will definitely add to the UI and make it easier for the users to understand what the "theme" is.

**Comment by amanjaiman1** [comment]
Welcome @khushiminda , i want to ask which page you want to change , and if you can elaborate on discord it will be better.

**Comment by khushiminda** [comment]
Sure sure sure pls come on discord today? Anytime after 8 ??
8929000861
Ping me on wp
