### ISSUE TITLE
Improving User Experience and behaviour

### ISSUE THREAD

**Issue by neeraj542** [amanjaiman1/Product_3D#8]
Here, I noticed that several buttons are used for different functionalities to enhance the user experience. However, I can assist you in further improving it by adding alternate text to each button. The buttons include: File Download, File Upload, Apply DalleAI, and Color Picker. If you find this helpful, please assign me the task so that I can make the necessary improvements.

![3d-Product](https://github.com/amanjaiman1/Product_3D/assets/114648043/7e3c1cea-0275-4814-829a-20b057ed46fd)

**Comment by amanjaiman1** [comment]
Lets do it but if you can make the customization page more better in UI, it will be great and this request is on my behalf. Do not worry if you're not available to do that 😊.

**Comment by neeraj542** [comment]
I'm available and ready to work on enhancing the UI of the customization page.

**Comment by amanjaiman1** [comment]
@neeraj542 you wanna work on the customizer page or i have to close this ?
