### ISSUE TITLE
Designing space for logo on T-shirts  for better user experience .

### ISSUE THREAD

**Issue by HumbleFool830** [amanjaiman1/Product_3D#85]
we need to give better experience for customers right , we need to add some features to logo . when ever is user is clicking on full that logo is applied for total t- shirt and also when ever user is clicking on logo it is applied for some portion only . **we need to take inputs form the user like width and heigth later we are applying that logo to that portion and also we will do something like 3d Design's also it comes with shadow too.**

can I work on this issue @amanjaiman1 please let me know ?

**Comment by amanjaiman1** [comment]
Yes you can and you are on right time buddy , go ahead !
