### ISSUE TITLE
ADD NEW LOOK TO THE README 

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [amanjaiman1/Product_3D#9]
I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

**Comment by Ayush-Tibrewal** [comment]
@amanjaiman1 PLEASE ASSIN ME WITH THE ISSUE

**Comment by creator79** [comment]
I am interested in working on issue [issue number or title] in the GSSSOC  23open source project. I have experience with relevant skills or knowledge Please let me know if this issue is still available.

**Comment by amanjaiman1** [comment]
@creator79 yes you can do more implementation but it will be better
