### ISSUE TITLE
[GSSOC'23] Footer Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [amanjaiman1/Product_3D#90]
This website also need Footer Section . 
 
**Why Footer Section is important? -:**

1. Navigation and Site Map: The footer provides easy navigation and a site map, helping users find information quickly.

2. Contact Information: Display important contact details like phone numbers, email addresses, and social media links.

3. Additional Links and Resources: Showcase related links, partners, and important pages that don't fit in the main navigation.

4. Copyright and Legal Information: Include copyright notices, disclaimers, and terms of service to protect intellectual property and ensure compliance.

5. Design Consistency and Branding: Maintain a unified design with the website logo, brand colors, and a brief description in the footer.

**Comment by parthpathakpp1** [comment]
Can you assign this issue to me under GSSOC'23.

**Comment by amanjaiman1** [comment]
> Can you assign this issue to me under GSSOC'23.

I will
