### ISSUE TITLE
Toggle switch for light dark mode instead of theme

### ISSUE THREAD

**Issue by karthiknadar1204** [amanjaiman1/Product_3D#95]
Proposed solution:
Replacing the Theme button with a toggle switch and place it on the navbar next to the sign in button on the left.
Further more make the navbar more attractive with some box shadow to make a proper demarkation between the navbar and the rest of the page and enhance the hover effect on the navbar and also to include the navbar in the light/dark theme mode. To do this i think we could make the navbar translucent and a lower opacitty so the dark/light toggle doesnt affect the navbar much but has atleast some effect .
This is because entire screen turning black except for the navbar looks bad.
Make the navbar sticky so it is consistent with users scrolling.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by amanjaiman1** [comment]
Go ahead

**Comment by karthiknadar1204** [comment]
@amanjaiman1 I have added the toggle switch , it works dynamically to switch between light and dark mode, but the issue is the customizer button on the button left gets hit with the similar styling applied to the theme button on the top right, cant seem to find the cause for that.
Will try adding the toggle switch to the navbar and submit pr

**Comment by karthiknadar1204** [comment]
I was thinking of removing the navbar contents from the html page and create a completely different component in a jsx file, that way, we can customize it much more easily while integrating the toggle switch with it, right now there are too many overlapping styles making it hard to manage.
Does that work @amanjaiman1 ?

**Comment by Lostlagend** [comment]
``Yes, that’s a great idea! Moving your navbar contents into a separate JSX component can make it much easier to manage and customize. It helps in several ways:

Separation of Concerns: By separating the navbar into its own component, you isolate its logic and styling, making it easier to understand and maintain. This also makes it easier to reuse the navbar component elsewhere if needed.

Customization: A dedicated JSX component for the navbar allows you to encapsulate its styles and logic, making it simpler to implement and manage features like a toggle switch.

Readability: Your main HTML or JSX file will be cleaner and more focused on the layout and structure of the page without the added complexity of the navbar’s implementation details.

Integration: Integrating a toggle switch or any other interactive elements within the navbar becomes more straightforward when it's encapsulated in a component. You can manage the state and events related to the toggle switch directly within this component. @karthiknadar1204 
``// Navbar.jsx
import React, { useState } from 'react';
import './Navbar.css'; // Assuming you have a separate CSS file for styling

const Navbar = () => {
  const [isToggled, setIsToggled] = useState(false);

  const handleToggle = () => {
    setIsToggled(!isToggled);
  };

  return (
    <nav className={`navbar ${isToggled ? 'toggled' : ''}`}>
      <div className="navbar-content">
        {/* Your navbar content here */}
        <button onClick={handleToggle} className="toggle-switch">
          {isToggled ? 'On' : 'Off'}
        </button>
      </div>
    </nav>
  );
};

export default Navbar;
