### ISSUE TITLE
Add a contact us page

### ISSUE THREAD

**Issue by karthiknadar1204** [amanjaiman1/Product_3D#96]
The current link on the navbar doesnt direct us anywhere, I was thinking of creating a new page to which we shall be directed on clicking the contact us page.

As for the contents of the page, I might need some input from your side as to what do you want to include in the page.

**Comment by amanjaiman1** [comment]
Go ahead

**Comment by karthiknadar1204** [comment]
@amanjaiman1 Do you have anything specific to be added to the contact page, please share that

**Comment by amanjaiman1** [comment]
Make accordingly to you , add Project Admin and mentors , contributors.

**Comment by creator79** [comment]
@karthiknadar1204  bro can i work on this issue what should i think Design a contactUs Page  using Three.js /fiber and Integrate a Email.js for Receiving a email @amanjaiman1 @SurajPratap10  what about your opnion guys??

**Comment by karthiknadar1204** [comment]
That works @amanjaiman1

**Comment by amanjaiman1** [comment]
> @karthiknadar1204  bro can i work on this issue what should i think Design a contactUs Page  using Three.js /fiber and Integrate a Email.js for Receiving a email @amanjaiman1 @SurajPratap10  what about your opnion guys??

Emm ok you can go ahead

**Comment by karthiknadar1204** [comment]
So are we working together @creator79

**Comment by amanjaiman1** [comment]
You both can do collaboration and then make the page next level

**Comment by creator79** [comment]
@SurajPratap10   @amanjaiman1  in the gssoc guideline how our contribution will count  can you tell me about these

**Comment by karthiknadar1204** [comment]
Same doubt

**Comment by karthiknadar1204** [comment]
I had a few ideas i thought we could implement,will share the details tomorrow morning first thing

**Comment by creator79** [comment]
@karthiknadar1204 kk fine bro first mentor will clear the conflict we can work together

**Comment by parthpathakpp1** [comment]
> The current link on the navbar doesnt direct us anywhere, I was thinking of creating a new page to which we shall be directed on clicking the contact us page.
> 
> As for the contents of the page, I might need some input from your side as to what do you want to include in the page.

@karthiknadar1204 @creator79 have some doubt need help .

**Comment by karthiknadar1204** [comment]
@amanjaiman1 I was thinking that how about we convert the contact us page into the contributors page with list of all the contributors with their photo,twitter lin, linkedin link and github link, we put all of this and make it into a card.

As for the contributors details, we can have the contributors update their info in a json file and we can extract it from the json file.
What do you think of this.
And as @creator79 sugested the email option, we could provide it on the side of this page.

What do you think about this

**Comment by karthiknadar1204** [comment]
on the top of the page, we will have the maintainers details, following thatt, we can have the rest of the details embedded

**Comment by amanjaiman1** [comment]
Right , uhm i have an idea so please contact me on discord ASAP

**Comment by karthiknadar1204** [comment]
Sure

**Comment by amanjaiman1** [comment]
Why you are asking, just do it
